
package Visao;

import DAO.ConnectionFactory;
import Entidades.Pessoa;
import Entidades.RespFinFisico;
import Entidades.RespFinJuridico;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;


public class PacientesPorRF extends javax.swing.JFrame {

    class registro {

        int id;
        String nome;
        String email;

        public String[] getinfo() {
            String[] info = {"" + id, nome, email};
            return info;
        }
    }
    Pessoa respfin;
    ArrayList<registro> lista;

    public Object[][] getArray() {
        ArrayList<registro> ls = getRegistros();
        int length = ls.size();
        Object[][] s = new String[length][3];
        for (int i = 0; i < length; i++) {
            registro r = ls.get(i);
            for (int y = 0; y < 3; y++) {
                switch (y) {
                    case 0:
                        s[i][y] = "" + r.id;
                        break;
                    case 1:
                        s[i][y] = r.nome;
                        break;
                    case 2:
                        s[i][y] = r.email;
                        break;
                }
            }

        }

        return s;
    }

    public ArrayList getRegistros() {
        ArrayList<registro> ls = new ArrayList();
        Connection con = new ConnectionFactory().getConnection();
        String sql = "";
        if (respfin instanceof RespFinFisico) {
            sql = "SELECT Pessoa.id, Pessoa.nome,Pessoa.email "
                    + "FROM Pessoa JOIN Paciente ON "
                    + "    Pessoa.id = Paciente.id JOIN RespFinFisico ON "
                    + "        Paciente.respfin = RespFinFisico.id "
                    + "    WHERE RespFinFisico.id = '" + respfin.getidPessoa() + "'";
        } else if (respfin instanceof RespFinJuridico) {
            sql = "SELECT Pessoa.id, Pessoa.nome,Pessoa.email "
                    + "FROM Pessoa JOIN Paciente ON "
                    + "    Pessoa.id = Paciente.id JOIN RespFinJuridico ON "
                    + "        Paciente.respfin = RespFinJuridico.id "
                    + "    WHERE RespFinJuridico.id = '" + respfin.getidPessoa() + "'";
        }
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                registro r = new registro();
                r.id = rs.getInt("id");
                r.nome = rs.getString("nome");
                r.email = rs.getString("email");
                ls.add(r);
            }
            ps.close();
        } catch (SQLException e) {
            System.out.println("Erro " + e);
        }
        return ls;
    }

    /**
     * Creates new form PacientesPorRF
     */
    public PacientesPorRF(Pessoa p) {
        respfin = p;
        initComponents();
        if (respfin instanceof RespFinFisico) {
            label.setText("Responsável:");
        } else if (respfin instanceof RespFinJuridico) {
            label.setText("Empresa responsável:");
        }
        visor.setText(p.getnome());

    }

    public PacientesPorRF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. Thhe content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        visor = new javax.swing.JTextField();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listagem de pacientes por responsável financeiro");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            getArray(),
            new String [] {
                "ID do paciente", "Nome do paciente", "E-mail do paciente"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        visor.setEditable(false);
        visor.setEnabled(false);
        visor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visorActionPerformed(evt);
            }
        });

        label.setText("Responsável");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(visor))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void visorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PacientesPorRF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PacientesPorRF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PacientesPorRF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PacientesPorRF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PacientesPorRF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField visor;
    // End of variables declaration//GEN-END:variables
}
